### ISSUE TITLE
Question: is it suitable for search menu?

### ISSUE THREAD

**Issue by zhaoyao91** [szhsin/react-menu#1]
By now triggers in all demos are buttons, is this component suitable for input trigger to make things like this?
https://ant.design/components/select/

**Comment by szhsin** [comment]
Hi @zhaoyao91 ,
Thanks for your feedback.

Currently, this use case cannot be realised as menu will grab focus after being opened. It's important to keep focus within the menu so that it can maintain correct internal states. This conflicts with the focus of a text input control. (i.e. input will lose focus after menu is open and user cannot continue to input text). 
The closest example is to put the input inside a menu item so that focus can be properly managed. You can see an example at: https://szhsin.github.io/react-menu/#focusable-item

Anyway, I think this use case is beyond the scope of menu and is better implemented with a select control (which belong to the form category).

**Comment by zhaoyao91** [comment]
thanks for your anwser @szhsin ~
