### ISSUE TITLE
ControlledMenu, but SubMenu is another ControlledMenu

### ISSUE THREAD

**Issue by oceanvievv** [szhsin/react-menu#1001]
React/React-dom version: 18.2.0
React-Menu version: 3.5.2

I'm building a simple controlled menu and a button, which controls whether this menu is open or not. Inside this menu I have an another dropdown menu built with the same approach like the first one. Everything works fine until I click on MenuItem inside dropdown and then  both menus are closed. Is it possible to close only the current menu (dropdown)?

**Comment by szhsin** [comment]
Hey @oceanvievv , looks like you have an uncommon use case. It will be great if you can provide a simple CodeSandbox example of it. 
Also, what's the reason you are not using the provided submenu component from this library?

**Comment by szhsin** [comment]
The parent menu closes after the child menu is clicked, because focus has moved outside of parent menu. 

All we need to do is restoring focus to something inside the parent menu. For example, set focus back to the button that has triggered the child menu.

Here is an update of your [CodeSandbox example](https://codesandbox.io/s/react-menu-1001-n8j92d?file=/src/App.js:1364-1405).

That said, the submenu created this way in the above example doesn't have good keyboard interaction support, compared to the `SubMenu` component provided by this library. If your use case is to make submenu controlled so that it can be open or close programatically by something else in the page, you can use the `instanceRef` instead.

Here is [another example](https://codesandbox.io/s/react-menu-1001a-4nvq64?file=/src/App.js) that achieves the same requirement with full keyboard navigation support.

**Comment by oceanvievv** [comment]
Thank you very much @szhsin! Appreciate it ❤️
