### ISSUE TITLE
Generate child components without higher order components?

### ISSUE THREAD

**Issue by gang-qiu-social-chorus** [szhsin/react-menu#108]
Hi there, from the docs it seems that the only way to use wrapped child components is via higher order components and `applyHOC()`. I tried it and was able to get it to work... but it took many hours and in general I find the HOC approach very cumbersome and unintuitive. Sadly if HOC's are the only way to generate child components I'm afraid it'll be a dealbreaker for my use case.

I was wondering if there is any way to do a more "traditional" approach to using wrapped child components? Something like the following example. I know there is an internal validation that will fail if I try this. Is there a way to perhaps turn off the validation (of course I would take care to only return the proper elements)?
Sandbox link: https://codesandbox.io/s/cool-sara-uqgqe?file=/src/App.js
```
const MyMenuItem = (text) => <MenuItem>{text}</MenuItem>
const App = () => (
  <Menu>
       <MyMenuItem text="hello" />
  </Menu>
)

// returns the following validation error...
The permitted children inside a Menu or SubMenu are MenuDivider, MenuHeader, MenuItem, FocusableItem, MenuRadioGroup, SubMenu. If you create HOC of these components, you can use the applyHOC or applyStatics helper, see more at: https://szhsin.github.io/react-menu/docs#utils-apply-hoc 
```
thanks in advance.

**Comment by szhsin** [comment]
Hi @gang-qiu-social-chorus , you don't need `applyHOC()` for your use case because you are not creating an HOC of `MenuItem`.

The validation is to ensure `MenuItem` is a DIRECT child of `Menu` in React component tree. `Menu` communicates with `MenuItem` for correctly maintaining a number of state (hover/focus/active) and keyboard navigation. You are free to put anything wrapped inside `MenuItem` as `children`. Think of `MenuItem` acts of a middle man between `Menu` and its children(your code) and helps encapsulate a lot of details that a menu library should be doing.

So, instead of doing:
```jsx
const MyMenuItem = (text) => <MenuItem>{text}</MenuItem>
const App = () => (
  <Menu>
       <MyMenuItem text="hello" />
  </Menu>
)
```
You need to do:
```jsx
const AnyComponent = ({ text }) => <>{text}</>
const App = () => (
  <Menu>
      <MenuItem>
          <AnyComponent text="hello" />
      </MenuItem>
  </Menu>
)
```
This should not be cumbersome if you create menu items using `Array.map`.

If you create menu items individually and don't want to repeat the outer `<MenuItem>` every time, just a little tweak of your pattern and make the function return `MenuItem` rather than a new component wrapping `MenuItem` inside:
```jsx
const myMenuItem = (text) => <MenuItem>{text}</MenuItem>
const App = () => (
  <Menu>
       {myMenuItem('hello')}
       {myMenuItem('world')}
  </Menu>
)
```
