### ISSUE TITLE
Adjust Menus to support transparent blur background

### ISSUE THREAD

**Issue by danielpaz6** [szhsin/react-menu#1123]
I tried to adjust the css file to support backdrop-filter, but only one working at a time, I looked up on the internet and a working solution was to use ::before element (https://stackoverflow.com/questions/56782369/only-one-backdrop-filter-working-at-a-time)

The issue starts when trying to do use that ::before element on a overflow auto container, when scrolling it just doesn't appear anymore.

An example: [codesandbox.io/s/react-menu-combined-forked-m36h9z](https://codesandbox.io/s/react-menu-combined-forked-m36h9z)

There may be few ways to solve the issue, but perhaps there could be an additional div element between .zsh-menu and the actual `<li>` elements? in that way, maybe the ::before element won't need to be used?

Another solution would be to expose an API to get the height of the scrollable element, something like that:
```js
const menu = document.querySelector('.menu');
const fullHeight = menu.scrollHeight;
```

**Comment by szhsin** [comment]
This issue is related the discussion [backdrop-filter not working for nested elements in Chrome](https://stackoverflow.com/questions/60997948/backdrop-filter-not-working-for-nested-elements-in-chrome).

One workaround is to use css pseudo element. However it doesn't work for elements with overflow that can scroll. To overcome it, we could change the DOM structure in order for two elements not nesting each other.

To achieve that, you may provide parent menu (root menu in the example) with prop `overflow="auto"`. This forces all menus to render flattened under the same container in DOM and the solution doesn't require pseudo elements any more. 
https://codesandbox.io/s/react-menu-1123-633md2

You could consider it as a hack at the moment but it solves the problem. In the mean while, I'm considering adding a new prop specifically for this purpose.

**Comment by danielpaz6** [comment]
This is great! thanks
