### ISSUE TITLE
Webpack 5 no longer supports process in frontend code

### ISSUE THREAD

**Issue by martinbroos** [szhsin/react-menu#114]
Users could add the polyfill themself but webpack recommends that process is no longer used.
https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advises -> Level 5: Runtime Errors

React-menu contains this line where it breaks:
`const isProd = process && process.env && process.env.NODE_ENV === 'production';`

It looks like your using it to help the developer and throw warnings. I'm not sure how you can add a better detection for development mode in webpack. There are some tips in the migration guide.

**Comment by szhsin** [comment]
Hi @martinbroos , thanks for your feedback.

The idea of detection for development env was borrowed from [react-redux](https://github.com/reduxjs/react-redux/blob/95e328753cd799ad17382c8fb09d81fed38ea779/src/hooks/useSelector.js#L110).
This detection is widely used in `react-redux`, and as it's a hugely popular library I expect it's not causing problems in most current project environments.

**Comment by gcangussu** [comment]
@szhsin The approach used by react-redux works on webpack 5 because by default it'll replace references to `process.env.NODE_ENV` by the string `'production'` or `'development'`, depending on the compilation mode.

The mistake here is referencing only `process` and `process.env`. Webpack 5 doesn't polyfill the global `process` object, it only replaces strict references on the code of `process.env.NODE_ENV` to the strings.
