### ISSUE TITLE
Menu loses focus when active menu item is filtered out. Now clicking outside does not close the menu until the menu is focused again

### ISSUE THREAD

**Issue by nmanandhar** [szhsin/react-menu#116]
Hi
Not sure if the use case is supported. What I am trying to do is to have a menu with a search input, but I also want the user to be able to type and filter even when the search input is not active. 
See https://codesandbox.io/s/wizardly-shamir-rrcxy?file=/src/App.js

In this case, when a menu item is active and I type and filter out the the active menu item,  If the number of items becomes less than the last active menu index, then the menu loses focus, but is not closed. Clicking outside does not close the menu as well.
Since the menu is not focussed, it does not handle keyboard events

I was expecting the menu to not lose focus
![bug2](https://user-images.githubusercontent.com/9746042/114260839-efda5580-99f6-11eb-95ac-ab0393572730.gif)

**Comment by szhsin** [comment]
Hi @nmanandhar , thanks for your feedback.

In the example, you add `onKeyDown` handler on the `Menu` which interferes with menu's internal focus management and cause bugs. 
The use case you mentioned is not supported because menu item will grab focus once being hovered. Supporting filter with a text input is considered as one perk of the library but not an emphasis from a menu library's perspective. Your use case  more resembles a select form control and is offered by other libraries such as the `react-select`.

You might be able to hook up additional event handlers and implement this use case, but I consider it's out of scope of this library.
