### ISSUE TITLE
how to open submenu programmatically?

### ISSUE THREAD

**Issue by terlan4** [szhsin/react-menu#1160]
Hi, when I click on Menu button I would like to see "Edit" and "Find" submenus open. How can I achieve it? Thanks

![image](https://github.com/szhsin/react-menu/assets/138553763/062116d4-54a4-41dd-9e3b-b86677efb2a6)

**Comment by szhsin** [comment]
The menu of this package has never been designed to work in this way, as it's not the expected behaviour of menus we've seen in most systems.

Still, it could be achieved by the `instanceRef` prop of a submenu. 

[Here is an example](https://codesandbox.io/p/sandbox/react-menu-1160-tl7xqd) with one level of submenu. You could do the same for multiple levels of submenus.
