### ISSUE TITLE
Is there a way to override the Icon itself via style-components

### ISSUE THREAD

**Issue by developerwok** [szhsin/react-menu#120]
Is there a way to override the Icon itself via style-components?

**Comment by szhsin** [comment]
Hi @developerwok , the icons are created with CSS pseudo-element and totally overridable.

E.g, remove the checkbox and radio item marks:
```jsx
const MyMenuItem = styled(MenuItem)`
  &.rc-menu__item--type-checkbox::before,
  &.rc-menu__item--type-radio::before {
    display: none;
  }
`;
```

The only tricky one is the submenu arrow, you will need to target it in the `Menu` component:
```jsx
const MyMenu = styled(Menu)`
  .rc-menu__submenu > .rc-menu__item::after {
    display: none;
  }
`;
```

You can also import `core.css` instead of `index.css`, then there isn't any icon at all.
