### ISSUE TITLE
Modify the className for FocusableItem

### ISSUE THREAD

**Issue by yuki383** [szhsin/react-menu#1215]
## Background
Currently, the className for `FocusableItem` is set to `szh-menu__item`. Consequently, the styles applied to `MenuItem` also affect `FocusableItem`.

In various scenarios, it is desirable to distinguish the styles for `FocusableItem` and `MenuItem` as they present different UI components.

An illustrative example is provided in CodeSandbox:
[CodeSandbox Example](https://codesandbox.io/p/sandbox/react-menu-focusableitem-forked-8lpx92?file=%2Fsrc%2FApp.tsx)

## Suggestion
Propose changing the className for `FocusableItem` to `szh-menu__focusable-item`.

**Comment by szhsin** [comment]
Hey @yuki383 , thanks for your feedback.

I can understand the rationale behind it. However, the suggested solution will result in a breaking change and a major version bump which I'm hesitant about. The className has been there on `FocusableItem` since v1 and the change will impact all previous versions.

You still have a few solutions to the current problem:

- Use `.szh-menu__item` to apply styling to all items (including `FocusableItem`), and use `.szh-menu__item--focusable` to override the css that doesn't apply to `FocusableItem`.
- or, use `.szh-menu__item:not(.szh-menu__item--focusable)` to exclude `FocusableItem` from the rest of other menu items.
- or, use custom class names instead of the built-in ones for your components:
```jsx
const MyMenuItem = (props)=> <MenuItem {...props} className="my-menuitem"/>
```
then apply css using:
```css
.my-menuitem {
  /* ...  */
}
```

I understand all the hassle shouldn't be there if we have made the right design decision in the first place. But it's still a rather trivial issue that can be solved in many ways. 

I'm closing the issue for now. We might revisit it in the next major release.
