### ISSUE TITLE
Position regression in v4.2.1

### ISSUE THREAD

**Issue by elringus** [szhsin/react-menu#1367]
I've started experiencing menu position/transform bugs in v4.2.1 and later (tested in 4.2.2 as well):

https://github.com/user-attachments/assets/75ca7bca-9c34-4998-a5e4-d391a2c77136

The menu randomly appears out of the window bounds and may or may not re-position inside the window.

This doesn't happen in v4.2.0.

**Comment by szhsin** [comment]
hey @elringus , this looks pretty unusual. 

Can you please provide info about the props configuration, hopefully a reproducible sandbox example?

did you get [this warning](https://github.com/szhsin/react-menu/blob/31bd25ef7e90abd3a6c176ba62414efef2d5d4b2/src/components/MenuList.js#L164) in the development environment?

**Comment by elringus** [comment]
Hi, Thanks for getting back!

Here is the wrapper I'm using over the `@szhsin/react-menu` (sorry for the unrelated code, I'll see if I can isolate it to a repro):

```ts
import { useState, useRef, ReactNode, MouseEvent, useLayoutEffect, useCallback } from "react";
import { c, BlurUnderlay } from "utilities";
import { Menu as SzhMenu, MenuButton as SzhMenuButton, MenuChangeEvent, MenuInstance } from "@szhsin/react-menu";
import { tip } from "components/tooltip";
import { MenuAlign } from "./types";
import "@szhsin/react-menu/dist/core.css";
import css from "styles/menu.module.css";

type Props = {
    label?: string;
    icon?: ReactNode;
    tooltip?: string;
    children?: ReactNode;
    buttonClass?: string;
    openButtonClass?: string;
    disabledButtonClass?: string;
    align?: MenuAlign;
    disabled?: boolean;
    handleOpen?: () => unknown;
    handleClose?: () => unknown;
};

export const Menu = ({
    align, buttonClass, children, disabled,
    disabledButtonClass, handleClose, handleOpen, icon, label, openButtonClass, tooltip
}: Props) => {

    const [open, setOpen] = useState<boolean>(false);
    const ref = useRef<MenuInstance>(null);
    const buttonRef = useRef<HTMLElement>(null);
    const alignType = align === MenuAlign.End ? "end" : "start";

    const handleMenuChange = useCallback((evt: MenuChangeEvent) => {
        if (disabled) return;
        setOpen(evt.open);
        if (evt.open) handleOpen?.();
        else handleClose?.();
    }, [disabled, handleClose, handleOpen]);

    const handleClick = useCallback((event: MouseEvent) => {
        if (!open) buttonRef.current?.blur();
        event.preventDefault();
        event.stopPropagation();
    }, [open]);

    const renderButton = useCallback(() => {
        const btnIcon = icon == null ? null : <span className={css.menuIcon}>{icon}</span>;
        const btnLabel = label == null ? null : <span className={css.menuLabel}>{label}</span>;
        const className = c(
            buttonClass,
            [open, openButtonClass],
            [disabled, css.disabledButton],
            [disabled, disabledButtonClass]);
        return (
            <SzhMenuButton {...tip(tooltip)} className={className}
                           onClick={handleClick} ref={buttonRef}>
                {btnIcon}{btnLabel}
            </SzhMenuButton>
        );
    }, [buttonClass, disabled, disabledButtonClass, handleClick,
        icon, label, open, openButtonClass, tooltip]);

    const renderChildren = useCallback(() => open && children &&
        <BlurUnderlay show={true}
                      className={css.itemsContainer}
                      children={children}/>, [children, open]);

    useLayoutEffect(() => {
        ref.current?.closeMenu();
        setOpen(false);
    }, [disabled]);

    return <SzhMenu instanceRef={ref}
                    children={renderChildren()}
                    menuButton={renderButton()}
                    onMenuChange={handleMenuChange}
                    className={disabled === true ? css.disabledMenu : undefined}
                    align={alignType}
                    gap={1}/>;
};
```

**Comment by szhsin** [comment]
Thanks for providing the sample code.

I have to point out this is not the intended way to consume this menu library in general and the code promotes some anti-patterns we do not encourage.

The  `<Menu/>` manages an internal state to indicate whether it's open or not. The code tries to copy this internal state into another local state (`open`) by listening to the `onMenuChange`. At the time when the internal open state becomes true, the menu will compute position, but the locally-copied `open` state is not true yet. So there is nothing to be positioned as the `children` is conditionally rendered based on the local state `open`.

The code worked in v4.2.0 because we had a re-position logic in response to menu resizing which corrected it anyway. However, this was never an intention here as the menu has not been resized in this case. In v4.2.1 we refactor the logic to run re-position only when the internal open is true. Therefore the above code could miss both the position opportunities.

I would recommend using the [ControlledMenu](https://szhsin.github.io/react-menu#controlling-state) if your use case relies on the `open` state. However, as you have already gone so far the smallest refactor would be using the render prop which exposes the internal state from the menu.
```jsx
    const renderChildren = useCallback((props) => props.state !== 'closed' && children &&
        <BlurUnderlay show={true}
                      className={css.itemsContainer}
                      children={children}/>, [children, open]);
```
```diff
- children={renderChildren()}
+ children={renderChildren}
```

**Comment by elringus** [comment]
Thank you very much for the details and the suggested fix! It worked perfectly.
