### ISSUE TITLE
What is the expected positioning of the arrow indicator when the MenuButton gets larger

### ISSUE THREAD

**Issue by smitser** [szhsin/react-menu#1373]
React/React-dom version: 16.14.0
React-Menu version: 4.2.2.

I am wondering what the expected position should be for the arrow indicator when the MenuButton contains more text than the examples (Menu, top, bottom, ...) or even when the MenuButton has a given width. 

I made the assumption that when setting the `align` property on the Menu to start or end that the arrow indicator would be positioned on that side of the MenuContainer. When looking at a Menu with more text, the arrow seems to move further to the middle. I expected it to stay at the same position.

CodeSandbox: https://codesandbox.io/p/sandbox/react-menu-starter-forked-f658r9

If this is expected behavior, is there a way to keep the arrow indicator at the same alignment as the align property?

**Comment by szhsin** [comment]
The arrow is expected to point to the centre of the anchor (menu button) irrespective of the menu alignment. `align` prop only has effects on the menu but not the arrow. 

I feel this should be the most sensible behaviour because logically the arrow always points toward the anchor element. One of the other examples we can find is [floating ui](https://floating-ui.com/docs/arrow), which has the same behaviour.

If you wish to override this behaviour or slightly adjust the arrow position, you may apply a `margin-left` (for vertical menu) or `margin-top` (for horizontal menu) on the arrow element.

**Comment by smitser** [comment]
Okay, thanks for the explanation!
