### ISSUE TITLE
Question: Hide menu on click outside of menu

### ISSUE THREAD

**Issue by bobbui** [szhsin/react-menu#188]
Is this possible to hide the menu when user click outside of menu, it is quite common behaviour. Pardon me if someone ask this before, I tried to search the issue but found nothing.

Any pointer would be appreciated!

**Comment by szhsin** [comment]
Hi @bobbui , 
menu will close/hide when user clicks outside and this is the default behaviour. You can see some examples at https://szhsin.github.io/react-menu/#basic-menu.

If your menu doesn't close, there might be one of these reasons:
- Forget to include `import '@szhsin/react-menu/dist/index.css';`

- You import `core.css` instead of `index.css`, but don't set `animation` prop on menu to `false`.

- You use `ControlledMenu` but don't set `isOpen` to false in `onClose` event. Here is a correct example: https://szhsin.github.io/react-menu/#managing-state

**Comment by bobbui** [comment]
@szhsin awesome, i am able to solve my problem
