### ISSUE TITLE
Is it possible to create Multi column Menu?

### ISSUE THREAD

**Issue by ajayvikas** [szhsin/react-menu#249]
Hi,

Is it possible to create Multi Column Menu. 

Also I would also like to create some part of the Menu Item to be Multi column, as shown in picture below.
![image](https://user-images.githubusercontent.com/15083089/131723018-4804d296-f592-44e5-b8e3-639966c2c4fb.png)

**Comment by szhsin** [comment]
Hi @ajayvikas , please see an example at https://codesandbox.io/s/react-menu-issue-249-wwoxd

Currently there are some restrictions on what can be children of menu component. 
Items which are part of keyboard loop should be wrapped in a `MenuGroup`;
Items which are not part of keyboard loop should be wrapped in a `MenuHeader`;

In the next release, these restrictions will be removed so that menu will accept any valid `jsx` elements as children.

**Comment by szhsin** [comment]
Updated [the example](https://codesandbox.io/s/react-menu-issue-249-wwoxd) with v2.0.1
