### ISSUE TITLE
ControlledMenu state issue ('open' to 'closed' transition)

### ISSUE THREAD

**Issue by CharlesCoqueret** [szhsin/react-menu#433]
In ControllerMenu, when managing the state externally, the initial transition from undefined or 'closed' to 'open', everything works fine.

It gets problematic when trying to close the menu.

**Description:**
Adjusting the state to 'closed' does not closes the menu.

**Step to reproduce:**
Click the button to open the menu
Click on the button once more to close the menu

Please find a reference to the case:
https://codesandbox.io/s/react-menu-bug-controlled-state-d6uun4?file=/src/App.tsx

**Snippet:**

```typescript
const ref = useRef(null);
  const [open, setOpen] = useState(false);

  const toggleMenu = () => {
    setOpen((prev) => !prev);
  };

  const closeMenu = () => {
    setOpen(false);
  };

  return (
    <div className="App">
      <div className="container">
        <div ref={ref} onClick={toggleMenu} className="button">
          Click to open 
        </div>

        <ControlledMenu
          state={open ? "open" : "closed"}
          anchorRef={ref}
          onClose={closeMenu}
        >
          <MenuItem>New File</MenuItem>
          <MenuItem>Save</MenuItem>
          <MenuItem>Close Window</MenuItem>
        </ControlledMenu>
      </div>
    </div>
  );
```

**Comment by szhsin** [comment]
Hi @CharlesCoqueret , the problem is that if the button is clicked while menu is open, menu will close as a result of losing focus. By the time button `onClick` event fires, menu is already in closed state so it will open again.

The solution is to use a `skipOpen` flag which is set `true` for a very short timeout after menu is closed due to losing focus. And open menu (not toggle it) in button `onClick` only after the timeout has elapsed. `ControlledMenu` has a `skipOpen` prop which makes this solution easier. https://codesandbox.io/s/react-menu-issue-433-cz32e6 (recommended)

Alternatively, you could implement similar logic in your code. https://codesandbox.io/s/controlledmenu-toggle-open-jd3u4

For a detailed explanation why this solution was chosen, please check out this thread: https://github.com/szhsin/react-menu/issues/56#issuecomment-778570673

**Comment by CharlesCoqueret** [comment]
Thanks a lot for you explanation.

👏 👏 👏
