### ISSUE TITLE
Compatibility along with text field focus

### ISSUE THREAD

**Issue by danielpaz6** [szhsin/react-menu#443]
Hi,

I'd like to use React-menu as Autocomplete feature to text field input.
I took as an example the Managing state: https://szhsin.github.io/react-menu#managing-state

And made some modification to make it work like Auto complete:

```jsx
const ref = useRef(null);
const [state, setState] = useState();

<input type="text" ref={ref} onFocus={() => setState('open')} />

<ControlledMenu state={state} anchorRef={ref}>
    <MenuItem>New File</MenuItem>
    <MenuItem>Save</MenuItem>
    <MenuItem>Close Window</MenuItem>
</ControlledMenu>
```

The problem: right now the accessibility is relied heavily on Focus (tabIndex), hence, even when mouse overring one of the Menu Items will cause the input text to lose focus.

I'd suggest to add new attribute to use internal state to mimic native focus for that special use case

**Comment by szhsin** [comment]
Hi @danielpaz6 , there were a few similar issues requesting this feature in the past, however, it's out of scope of this library and won't be implemented.

1. From accessibility's perspective, AutoComplete is a [listbox](https://www.w3.org/TR/wai-aria-practices/#Listbox) which has very different semantics from a [menu](https://www.w3.org/TR/wai-aria-practices/#menu).
2. To implement AutoComplete, focus must stay on the `<input/>` rather than individual menu item when navigating through items with keyboard. This will create several problems for a menu:

   - There is no good way to trigger event prop (onClick) on menu item unless it's done in an ugly/unconventional way (e.g. using an imperative ref). However this is not an issue for AutoComplete because usually there is no need to trigger event prop on dropdown options.
   - To be aria compliant, [`aria-activedescendant`](https://www.w3.org/TR/wai-aria-practices/#kbd_focus_activedescendant) should be used to manage focus instead of [roving `tabindex`](https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex). The `aria-activedescendant` implementation requires assigning a unique id to each item. Many solutions cause hydration mismatch bugs and that's why React 18 adds [a new API](https://github.com/reactwg/react-18/discussions/111) to solve the problem. Again, this might not be an issue for AutoComplete as people usually don't server render dropdown options.
   - Browser won't scroll the newly focused item into view and this work should be done additionally.

So, if you check out other popular component libraries, many of them implement Menu and AutoComplete as different components, and menu usually uses the [roving `tabindex`](https://www.w3.org/TR/wai-aria-practices/#kbd_roving_tabindex) solution.
