### ISSUE TITLE
React router support?

### ISSUE THREAD

**Issue by rvision** [szhsin/react-menu#5]
How to use this menu as navigational menu?

Adding href property skips router navigation. Adding nested `<Link />` inside `<MenuItem />` doesn't work.

I don't think there is a need for href prop at all. MenuItem children should be responsible for what is displayed as menu item and behaviour.

**Comment by szhsin** [comment]
Hi @rvision ,
There are two ways to work with React Router:
1. Add a `href` to `<MenuItem/>` which creates an `<a>` tag inside the menu item.
This solution works fine. However, it seems that page always reloads when using an `<a>` tag instead of `<Link/>` to change route with React Router.

If you feel it is undesirable, you have another option:
2. Wrap `<Link/>` in a `<FocusableItem/>`.

Please see [an example that demonstrates both approaches](https://codesandbox.io/s/react-menu-react-router-example-dw4ku).
The example also includes a little CSS style to make the two approaches look consistent.

The `href` prop of `<MenuItem/>` is to allow easily adding url to a menu item. It creates a DOM structure that strictly adheres to the [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices/#menu).
Additionally, wrapping `<Link/>` as direct children of `<MenuItem/>` works for mouse event, but you are not able to activate the link with keyboard.

Ideally, anything which is supposed to receive focus (`<Link/>` in this case) should be placed in a `<FocusableItem/>` instead of `<MenuItem/>`. Then focus can be properly managed so that keyboard interaction with menu item will work.
