### ISSUE TITLE
Menu items don't follow the MenuButton on scroll

### ISSUE THREAD

**Issue by moroshko** [szhsin/react-menu#59]
To reproduce:

1. Visit https://codesandbox.io/s/react-menu-scroll-issue-8o22f
2. Click "Open menu"
3. Scroll

When the whole page is scrolling, menu items follow the MenuButton as expected (like in the docs).

However, if you have some other container with `overflow: auto`, like in the CodeSandbox above, the menu items are getting detached from the MenuButton.

Is there a way to ensure that menu items always rendered next to the MenuButton?

**Comment by benatkin** [comment]
If you set the position of the scrollable container to `relative` and remove the `portal`, it follows the scrolling.

https://codesandbox.io/s/react-menu-scroll-issue-relative-iiswl

**Comment by moroshko** [comment]
@benatkin Removing `portal` seems problematic since the menu options are cut when the container is limited in width (which is exactly why I added `portal` in the first place): [Codesandbox](https://codesandbox.io/s/react-menu-scroll-issue-no-portal-p2ykg)

<img width="294" alt="Screen Shot 2021-02-16 at 1 08 05 pm" src="https://user-images.githubusercontent.com/259753/108009998-0c41bd80-7058-11eb-96a3-308884123628.png">

**Comment by szhsin** [comment]
Hi @moroshko @benatkin , thanks for your feedback.

Currently menu position is calculated based on the viewport size. Positioning menu within a specific container is not supported yet, that's why the default stylesheet sets `position: absolute` to menu's containing block. Will be adding this feature in the next release.

**Comment by szhsin** [comment]
@moroshko [v1.7.0](https://github.com/szhsin/react-menu/releases/tag/v1.7.0) released two props that should be able to solve your use case: https://codesandbox.io/s/react-menu-scroll-issue-no-portal-forked-berjd

**Comment by benatkin** [comment]
Great. @moroshko I knew that was just a workaround.

**Comment by mrudowski** [comment]
It works great @szhsin

by the way -  is it a built-in way to detected scrolling inside container with `overflow` and **close** the menu with `portal={true}` ? 

`viewScroll="close"` - unfortunately not work in that combination

I used this example to illustrate this:
https://codesandbox.io/s/react-menu-scroll-issue-no-portal-forked-n4cm5

(thanks again for the `portal` prop  : )

**Comment by szhsin** [comment]
Hi @mrudowski ,
I've considered the use case you mentioned above but don't feel like it should be something handled in this library. A possible implementation would require monitoring `scroll` event of all the ancestors which have `css overflow` all the way up to `document.body`.

The current design would handle two most common scenarios:
- Position menu bounded by viewport and close or reposition menu in response to scrolling of viewport.
- Position menu bounded by a container and close or reposition menu in response to scrolling of that container.

In situations you need a mix or mismatch of the above scenarios, you can use `ControlledMenu` and close menu when your code detects the container is scrolling.

**Comment by mrudowski** [comment]
Yes, I'm understand your concerns about library responsibility and I really respect that.

I'm just use a lot https://react-select.com/ and https://reactdatepicker.com/ and they work with portals that hide on scroll, and sooner or later it very handy solution. 

But as you say - it can be always implemented outside  - only when we need it.

**Comment by szhsin** [comment]
Thanks @mrudowski for the feedback.
Please see [an CodeSandbox example](https://codesandbox.io/s/react-menu-portal-scroll-close-p273g) for how to handle the container scrolling issue when `portal` is set. In the future, this handling might be integrated into the library with an extra prop.

**Comment by hazzo** [comment]
Maybe I'm late and wrong, but @szhsin with the three props that you make accessible in your library the codebox example can be achieved without controlled menu.

```jsx
<Menu
    viewScroll="close"
    boundingBoxRef={this.ref}
    portal
    {...restProps}
/>
```

Tested and working

**Comment by hazzo** [comment]
What I'm not able to make is offset the menu in X axis. If boundingBox is given the X Axis offset is not working.

**Comment by szhsin** [comment]
Hi @hazzo , when you give menu a `boundingBoxRef`, you usually don't need the `portal` anymore.
If you set `portal` and `boundingBoxRef` prop at the same time, menu will be mounted outside the bounding box but positioned within the bounding box, which doesn't make sense in most situations.

**Comment by hazzo** [comment]
Hmmm maybe I did not understand clearly how `boundingBoxRef` works. But imagen the following example: 

You have a small container that has `overflow: auto` so every element that pop ups inside of it can't exceed the container width or it will be cut off. So with portal you can take it outside of the container. But if you scroll the container the element and the menu gets desynchronised (it does not follow anchor to the element even though in the example it does) causing kind of a wired UI behaviour. So to avoid this I thought of hiding the menu on scroll and added `viewScroll="close"`. This way the viewScroll reacts to scroll of bounding box and not window.

Maybe there was a simpler solution but this did the trick. What do you think about it? 

Note: don't know why the menu does not follow the anchor element, maybe because I'm using a custom button?

**Comment by szhsin** [comment]
@hazzo , you can use it in this way, just be aware there are two issues in the example you described:

1. When `portal` is set, you probably will expect menu to break out the container and take advantage of the available space in the viewport. But menu is restricted to the smaller container box if the `boundingBoxRef ` prop is given at the same time. This might make menu detached from its anchor button unless you change the `position` props as well.
2. Menu will not close or reposition menu in response to scrolling of viewport.

Example: https://codesandbox.io/s/react-menu-portal-scroll-close-issue-59-fnu6t

The menu does not follow its anchor element because they are in two separate scrolling contexts when `portal` is set.

**Comment by hazzo** [comment]
> @hazzo , you can use it in this way, just be aware there are two issues in the example you described:
> 
> 
> 
> 1. When `portal` is set, you probably will expect menu to break out the container and take advantage of the available space in the viewport. But menu is restricted to the smaller container box if the `boundingBoxRef ` prop is given at the same time. This might make menu detached from its anchor button unless you change the `position` props as well.
> 
> 2. Menu will not close or reposition menu in response to scrolling of viewport.
> 
> 
> 
> Example: https://codesandbox.io/s/react-menu-portal-scroll-close-issue-59-fnu6t
> 
> 
> 
> The menu does not follow its anchor element because they are in two separate scrolling contexts when `portal` is set.
> 
> 

Yes I'm aware of this trade offs. What I'm not seem able to do is to apply an extra offset in the X margin if the offset is greater than the bounding container. I think that this is due to it uses the same offset implementation if the container is the viewport. So you have limited this offset to the container to avoid the menu going outside of the screen, right?

**Comment by szhsin** [comment]
@hazzo,  I don't quite get your use case. 
If you are referring to the `offsetX` and `offsetY` props and trying to use them to avoid menu button being overlapped by menu, I recommend you set the `direction` prop to 'right'.

If you mean `offsetX` and `offsetY` sometimes don't take effects, it's because when `position` prop is 'auto' (default value), the offsets are just indicative and have low preferences than positioning menu with the bounding box. 
Try to set `position` prop to 'anchor' or 'initial' and the offsets will be honoured.

**Comment by hazzo** [comment]
@szhsin Thanks for the advise! Yeah the use case is kind of tricky.
