### ISSUE TITLE
When using hover/keyboard searchbar loses focus.

### ISSUE THREAD

**Issue by mikaeljan** [szhsin/react-menu#618]
I have a filter/search bar as a first item, however when I use keyboard/hover over next items my filter/search bar loses focus and I can no longer type into it.

Is there a way how to fix focus on certain element even while moving up/down with keyboard or hovering over next menu 
items?

[Focusable item](https://szhsin.github.io/react-menu#focusable-item) example is a good example of a behaviour which loses focus when you are not hovering or move away from the input field using keyboard.

What I'd like to achieve is to have fixed focus on input field while "being elsewhere" within the select component.
Other libraries feature this quite commonly that is why I am surprised this library has a different behaviour with no way how to override it.

**Comment by szhsin** [comment]
Hi @mikaeljan,  conceptually the component you are looking for is a select (e.g. [React-Select](https://react-select.com/)) or auto-complete ([e.g. `MUI Autocomplete`](https://mui.com/material-ui/react-autocomplete/)). However, this is a menu library which implements the [ARIA menu pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu/). 

If you take a look at the menu libraries in the ecosystem, almost none of them support adding an input element in a menu item (e.g. [MUI menu](https://mui.com/material-ui/react-menu/)). 

This library actually goes beyond a bit to offer a search/filter experience with the [Focusable item](https://szhsin.github.io/react-menu#focusable-item). The feature exists to make it possible for some users who want to implement both filter/search and menu using a single library instead of two. The feature is considered an added perk of this library rather than a core functionality. You do need an addition select/auto-complete library if you want the selection experience.

Also, you could read [an explanation](https://github.com/szhsin/react-menu/issues/443#issuecomment-1061805356) of why the implementation makes the input element lose focus when another item in the menu is hovered.

**Comment by mikaeljan** [comment]
Thank you for the reply and the information provided
