### ISSUE TITLE
Cannot set max height when overflow is set to auto

### ISSUE THREAD

**Issue by lashax** [szhsin/react-menu#708]
For the `SubMenu` component I have set overflow to `auto`. When menu items overflow, the scrollbar is correctly added but the `max-height` property of the submenu container is always `100vh`. I tried to set `menuStyle` prop for `SubMenu` and `Menu` to no avail. It seems that `max-height` is recalculated on every render, so setting it from `menuStyle` does not work.

It would be good to be able to manage the maximum height of the menu as taking the entire height of the viewport is often visually unpleasant.

**Comment by szhsin** [comment]
Hello @lashax 

If you want a fixed maximum height for menu, you can use `menuStyle` prop or CSS stylesheet to apply the `max-height` and `overflow` rules. In this case, there is no need to specify the `overflow` prop on the `Menu` component.
https://codesandbox.io/s/react-menu-starter-forked-80pjxg?file=/src/App.js

Alternately, I recommend that you use the `overflow` prop with `boundingBoxPadding` which adds padding space around menu in the viewport, if the 100% height is visually unpleasant. 

For example, the group menu in this example has a 10-pixel padding around menu so that it doesn't touch the viewport edges.  https://szhsin.github.io/react-menu#menu-overflow

**Comment by lashax** [comment]
Thanks a lot!
