### ISSUE TITLE
How to always render the opened menu as the last element in document.body?

### ISSUE THREAD

**Issue by moroshko** [szhsin/react-menu#728]
Hey @szhsin,
First of all, thanks for this library!

I have a use case where a menu is rendered inside a modal and needs to be rendered on top of it. And, in the other instance, menu option is triggering a modal and then the modal needs to be rendered on top of the menu.

To achieve this, I'm relying on the DOM order of the menu and the modal, trying to avoid z-index wars.
In the first instance, I'd like the menu to be rendered after the modal:

**Use case 1 - menu on top of modal** (see CodeSandbox below)
```
  ...
  <div class="modal-overlay">...</div>
  <div class="szh-menu-container">...</div>
</body>
```
And, in the second one, the modal to be rendered after the menu:

**Use case 2 - modal on top of menu**
```
  ...
  <div class="szh-menu-container">...</div>
  <div class="modal-overlay">...</div>
</body>
```

However, as you can see in this [CodeSandbox](https://codesandbox.io/s/react-menu-portal-target-forked-ydsxjt?file=/src/App.js), the `szh-menu-container` is rendered before the modal, breaking use case 1 above. Why is this happening? 

Is there a way to always render the opened menu as the **last element** in the `document.body`.

**Comment by szhsin** [comment]
Hi @moroshko ,

The element position within `document.body` is determined by the rendering order of React components.
```jsx
export const Modal = ({ onClose, children }) => {
  return createPortal(
    <div className="modal-overlay">
      <div className="modal-dialog">
        {children}
        <button className="modal-close-button" type="button" onClick={onClose}>
          X
        </button>
      </div>
    </div>,
    document.body
  );
};
```
In the render method of `Modal` component,  the parameter of `createPortal` is evaluated before the function can be called. This causes the rendering of `children` and the render method of menu component to be called. The menu component invokes `createPortal` internally and renders `szh-menu-container` into `document.body`. Then the call stack returns to the `createPortal` in the `Modal` and renders `modal-overlay` after `szh-menu-container` in the `document.body`. 

It results in a reversed DOM order of JSX elements in render method and it's a natural result of using `createPortal` both in the parent and child components.

That being said, the reversed order won't cause an issue when a greater `z-index` is set on `szh-menu-container`, because modal and menu are positioned within the same [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

If you still feel strongly about the correct element position within `document.body`, I find a way to overcome it by setting the children of `Modal` in an `useEffect`. One downside is that it will cause an extra render of modal component.  Here is the example: https://codesandbox.io/s/react-menu-728-br7k9r?file=/src/App.js

**Comment by moroshko** [comment]
> That being said, the reversed order won't cause an issue when a greater z-index is set on szh-menu-container, because modal and menu are positioned within the same [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

I can't rely on having a greater z-index on szh-menu-container because this will break use case 2 above.

I'm curious, why `szh-menu-container` is rendered **before** the menu is opened? If you have a large table, say 1000 rows, where every row has a menu, this results in 1000 `szh-menu-container`s being rendered, whereas in reality, only one menu can be opened at a time.

Is it possible to append `szh-menu-container` to the body only when the menu is opened and need to be rendered?

**Comment by szhsin** [comment]
> Is it possible to append szh-menu-container to the body only when the menu is opened and need to be rendered?

@moroshko,  you have got the point. Yes, rendering the container into DOM only after the menu is open will fix this nuisance and some other issues like #2, #94

Currently the `szh-menu-container` is rendered in a parent component of the [`MenuList`](https://github.com/szhsin/react-menu/blob/master/src/components/MenuList.js). As React runs effect from child to parent upwards the tree, `szh-menu-container` is yet to be mounted when the effect for positioning menu runs in the `MenuList`. To overcome it, `szh-menu-container` is always rendered in the parent component even before menu is open.

You might wonder why we didn't put `szh-menu-container` in the render method of `MenuList`. It's because `MenuList` is also used by the submenu which doesn't need a container. 

I think this setup is causing enough trouble which worths some optimisation. Your question about the 1000 containers being uselessly rendered is also very valid. We'll make a fix in the upcoming release.

**Comment by moroshko** [comment]
Thank you @szhsin, looking forward to try the new release! Do you have a sense of when it might be available?

**Comment by szhsin** [comment]
The change is almost done in #729. Will update the unit tests/docs and do some package verification tomorrow. 

If you'd try it out early, there is an alpha version of [3.3.0-alpha.0](https://www.npmjs.com/package/@szhsin/react-menu/v/3.3.0-alpha.0) and the [codesandbox example](https://codesandbox.io/s/react-menu-portal-target-forked-iup2li).

**Comment by moroshko** [comment]
@szhsin `3.3.0-alpha.0` behaves as expected!

Small question: is there a good reason not to remove `szh-menu-container` from the DOM when the menu is closed?

**Comment by szhsin** [comment]
@moroshko thanks for confirming the updates. [v3.3.0](https://github.com/szhsin/react-menu/releases/tag/v3.3.0) is released!

To answer your question: menu by default is lazily mounted into DOM and remains mounted when closed. You could add the `unmountOnClose` prop to remove it from DOM: [CodeSandbox](https://codesandbox.io/s/react-menu-portal-target-forked-iup2li?file=/src/ActionsMenu.js)

**Comment by moroshko** [comment]
Awesome, thanks a lot for a quick turnaround!
