### ISSUE TITLE
Submenu still open when hovering over disabled menu items or custom element in the menu

### ISSUE THREAD

**Issue by AdamModus** [szhsin/react-menu#903]
React/React-dom version: 16.13.1
React-Menu version: 3.5.2

## Describe the bug
To be honest, I am not 100% sure if this is a bug report or a feature request. Feel free to change it to whatever suits you best.

This particular behaviour happens with submenus. If a submenu is open and you move your mouse over a disabled menu item or over anything custom within the menu (I added a footer div in the code sandbox as an example of that), the submenu opens. This is normal and expected behaviour.

After that, if you move the mouse outside the menu, the submenu remains open. Also wholly normal behaviour. However, I have noticed that if you move the mouse to a disabled or custom component, the submenu remains open.

## To Reproduce

1. Open a submenu
2. Hover over a disabled menu item or
3. Hover a custom element within the menu

## Expected behaviour

As a user, I would expect the submenu to close whenever I hover any element within the menu that is not the "submenu trigger menu item". I think this is the common expectation because it's what regular OS menus work (e.g. MacOS menus, Windows 11 menus).

## Code snippets/CodeSandbox examples/Screenshots

https://codesandbox.io/s/react-menu-starter-forked-r5bciy?file=/src/App.js

Feel free to use this sandbox to replicate the issue I mentioned!

**Comment by szhsin** [comment]
Hey @AdamModus , thanks for reporting the issue.

As you pointed out, the current submenu behaviour is not ideal and is different from native OS menus. It behaves as so that the implementation is simple. 

Aligning the behaviour with native OS menus will make the implementation more complex but is still doable. I think the efforts would be well worth the improved user experience. Hopefully I can work out a solution soon in the next release.

**Comment by AdamModus** [comment]
Thanks for looking into this @szhsin! If you need my help with anything, please let me know 🙂

**Comment by szhsin** [comment]
Fixed in v3.5.3

**Comment by AdamModus** [comment]
@szhsin , tested and it works perfectly. Thanks!
