### ISSUE TITLE
Clicking on parent menu closes and opens the submenu

### ISSUE THREAD

**Issue by nmanandhar** [szhsin/react-menu#95]
Clicking on the parent menu closes and opens the submenu. This causes some flickering and is not the behaviour I have seen in other menus (I checked in Intellij idea and vscode). Is there any way of keeping the submenu open instead of closing and opening the submenu.

**Comment by szhsin** [comment]
Hi @nmanandhar , thanks for your feedback. 
I understand this is not a good user experience and I'm glad you compare it with an OS-level menu component 😂.
It was implemented this way due to some technical difficulties, but I probably have a solution for it now and will make an improvement in a future release.

**Comment by szhsin** [comment]
Issue fixed in #107 , it will be included in the next release.
