### ISSUE TITLE
Keyboard shortcuts cascade into dialogs that are opened from a menu

### ISSUE THREAD

**Issue by milogert** [szhsin/react-menu#973]
React/React-dom version: 18.2.0
React-Menu version: 3.4.1

## Describe the bug

We are using `react-menu` to open some dialogs. When navigating the menu with the keyboard upon hitting enter the menu is dismissed, the dialog is opened, and then (unexpectedly) the dialog is submitted using the initially focused button.

We found a way around this by calling `e.syntheticEvent.preventDefault()` after we open the dialog. But we are confused why this works and why `e.syntheticEvent.stopPropagation()` didn't work.

The bug essentially is that this probably shouldn't happen by default. For us it was causing testers to submit dialogs without knowing what they said when using keyboard shortcuts.

## To Reproduce

1. Have a menu item that opens a `<dialog>` element.
2. Open the menu.
3. Arrow down to the only menu item.
4. Hit the Enter key.
5. Don't see any dialog but the menu goes away.

If you perform the same flow above but use your mouse the dialog will show up.

## Expected behavior

5. The dialog should show up.

## Code snippets/CodeSandbox examples/Screenshots

The link below shows both the broken version and the version with our workaround.

https://codesandbox.io/s/eloquent-pike-9w8gj3?file=/src/App.js

**Comment by szhsin** [comment]
Hi @milogert , thanks for reporting the issue.
We use keydown events to handle menu items activated by the "enter" key. If we focus another button in response to the "enter" key event, the button which just receives focus will fire an onClick event, unless we call `preventDefault` after handling the "enter" key.

I found the behaviour is not specifically tied to the menu library but rather this implementation method. For example, I create [a sandbox](https://codesandbox.io/s/react-menu-973-78d8zr?file=/src/App.js) which demonstrates the same behaviour. After an "enter" key event is handled on an input, the next focused button will fire an onClick event, unless `preventDefault` is called.

In your example, the first button of dialog will automatically receive focus after dialog is open, which results in a subsequent onClick event that closes the dialog.

I can understand calling `stopPropagation` wouldn't prevent it because the keyDown and click events are on two elements which don't have ancestor/descendant relationship in the DOM tree. I also don't quite understand why `preventDefault` works in this case. It might be a spec requirement or a discretion from browsers.

For the menu, we probably should handle this case by calling `preventDefault` for the "Enter" keyDown event. It could avoid causing confusion to users.

**Comment by szhsin** [comment]
Fixed by[ v4.0.1](https://github.com/szhsin/react-menu/releases/tag/v4.0.1)

`preventDefault` is called from the library so that consuming apps can expect a consistent behaviour for both mouse and keyboard interactions.

https://codesandbox.io/s/proud-paper-kgt65c?file=/src/App.js
